### ISSUE TITLE
domain 

### ISSUE THREAD

**Issue by bdolor** [BCcampus/tlpd#1]
- we need a subdomain for cert
- we need a domain name for production (registered through sfu)
- we need a certification (ssl) for production domain.

**Comment by alexpflores** [comment]
@BCcLeva This is a notification :)

**Comment by bdolor** [comment]
@BCcLeva - how is this going? any updates?

**Comment by BCcLeva** [comment]
Hi I'm ready to make some decisions but wanted to consult with Michelle and Tracy but 
both are not available until tomorrow AM. 

I'm leaning towards Registration that is more open as I thought about it and the account management part where 
it is manually done might be too restrictive ...and closed/controlly. 

The domain name...I've come up with a few ideas and just need to run them by a few people. That's where I'm at so far. 
Did you want to meet at all today? I meet with Michelle in AM and Tracy in early afternoon. so of my ideas for a domain name might be to take 
the profleaarn name since we are "retiring" it...or TLPD or I have few things up my sleeve.

**Comment by bdolor** [comment]
will wait until tomorrow. Let us know when something is official - thank you!

**Comment by BCcLeva** [comment]
Hi there question about the domain decision. I need to consult with Denise (as head of BCc cmms) and Tracy (internal client) I have a recommendation so I'm guessing we can decide fairly quickly.  

what's your thoughts about putting something in place and if we need to change ...do a redirect to the revised URL?

**Comment by bdolor** [comment]
I would say that there is more to consider than what a redirect might only partially rectify, since we're dealing with registering domains and certs to go a long with it there is overhead and technical debt that would make waiting for a final decision seem the better option.

**Comment by BCcLeva** [comment]
Ok let me see if I can fast track. The resource is something we will likely host and "own" going into the future which is informing my recommendation. I'm on it today.

**Comment by BCcLeva** [comment]
ok I've talked to Tracy and we settled on tlpd.bccampus.ca but this is pending a consultation with Denise (sending note now)

**Comment by BCcLeva** [comment]
Good morning sprinters...Denise is fine with our URL tlpd.bccampus.ca if we keep in mind some of Barb's thoughts and questions around 1. membership functionality (limitations?)  2. SEO strategy
I think of this as a standalone project not having the same constraints as what might exist for the BCc org. site but I may be speaking out of turn and need your help/expertise. Thanks!

Hi Denise, 
I haven’t been part discussions regarding URLs for the portal. 

As part of the web consolidation project we developed consolidation guidelines which I think we can apply to determining an appropriate URL and if it should be a subdomain or not. Here are the guidelines.
The rationale Leva has provided and the suggested name appears to fit with the “subdomain” category. I do think using a subdomain, tlpd.bccampus.ca, helps with branding the portal as BCcampus project. If it’s meant to be a standalone project, like the early years portal, then maybe a separate domain, without BCcampus.ca, might be considered. 

If there is a membership area, it may not be possible to set it up as a subdomain on BCcampus.ca due to technical reasons. That’s a Brad question for sure. 

On another note, when googling "teaching and learning proD”, many results show up. Which is to be expected. One thing to consider is the SEO strategy for the site it shows up high in google results and users and easily find it.

**Comment by bdolor** [comment]
is `tlpd.bccampus.ca` a go for cert or prod?

**Comment by BCcLeva** [comment]
Both.

**Comment by bdolor** [comment]
If I can make a suggestion for a cert domain, which _must_ be different from prod `tlpddev.bccampus.ca`

**Comment by BCcLeva** [comment]
Ok sure. I didn't realize. That's perfect.
