### ISSUE TITLE
matamo analytics on Prod

### ISSUE THREAD

**Issue by bdolor** [BCcampus/tlpd#18]
ensure that this is up and configured.

**Comment by bdolor** [comment]
complete on prod

**Comment by jgrajkowski** [comment]
Looks like the Piwik WP plugin is configured and is tracking data (including local, I think), though trying to access through Troy says otherwise, @bdolor. Thoughts?

"No analytics data has been tracked for this website yet. Please set up the tracking code below into your website or mobile app if you haven't done already.

This message will disappear as soon as some data was tracked for this website. In the meantime, maybe you would like to set up some goals or learn more about the features of Matomo in one of our guides or FAQs."

**Comment by bdolor** [comment]
let's stick with self-assignment please

**Comment by paulagaube** [comment]
The PIWIK URL in tlpd.bccampus.ca is going to https://helga.bccampus.ca/piwik/ and according to George, this is the "test" site for PIWIK. Do we need to change this URL in **Settings > WP-PIWIK >Connect to Piwik** to https://troy.bccampus.ca/piwik @bdolor?

**Comment by bdolor** [comment]
if you're looking at the settings in tlpddev, then it should be pointing to helga.

**Comment by bdolor** [comment]
appears to be working as intended 
![image](https://user-images.githubusercontent.com/2048170/46229795-a683f800-c31b-11e8-81bd-5c5afc0219c1.png)

**Comment by paulagaube** [comment]
DONE on Prod
