### ISSUE TITLE
Remove or Publish Draft Events in TLPD

### ISSUE THREAD

**Issue by paulagaube** [BCcampus/tlpd#181]
### Description 

There are quite a few "Draft" events in tlpd.bccampus.ca for upcoming events and it is not clear if these are duplicate events or events that weren't published for some reason.
We need to investigate and either remove the duplicate events or find out if the drafts need to be published. 

**Expected behaviour** 

There are very few draft events 

**Actual behaviour** 
There are currently 17 draft events

### Steps to reproduce the problem
Login to TLPD as an administrator, go to Events, view Draft events

### System Information

- TLPD: PRODUCTION site: May 23, 2019
- WordPress:

**Comment by kkilbey** [comment]
I have cleared out these draft events. Most were duplicates of live events, so I deleted the drafts.

The only exception was a draft by Cathy G. of an upcoming event that had not been published to TLPD. I emailed Cathy and she said yes, publish. So that event is now live, and all drafts are gone.

@paulagaube shall we close this ticket? :)

**Comment by paulagaube** [comment]
Checked out TLPD this morning and deleted two duplicate events in drafts.

Closing this ticket. 

We will create a procedure for doing regular maintenance checks on the TLPD site. (e.g., Monthly calendar reminder.)
