### ISSUE TITLE
Progressive Web App investigation 

### ISSUE THREAD

**Issue by bdolor** [BCcampus/tlpd#21]
investigate how PWA works in a multisite WP environment. 

- A lot of the functionality/custom is currently in the theme. I'm concerned about whether or not the PWA functionality can be delivered to two different sites in a multisite environment.

**Comment by alexpflores** [comment]
Long-term goal is to achieve the [PWA Baseline](https://developers.google.com/web/progressive-web-apps/checklist#baseline), if we are using EYPD as an example, there are a few things we'd still have to tackle as per the Lighthouse audit (does not respond to 200, loads slow on 3G, user will not be prompted to install the app). Keeping that in mind, we'll need a flexible way of adding this functionality and changing the configuration to make some things site specific (such as what happens, or what content gets display when they are offline). The following are two options to consider: 

**Share common theme on multi-site:**
Because our theme, and eypd, are child themes of CBOX unfortunately we'd be stuck with the PWA configurations in each themes functions.php file... this means we wouldn't realize the full benefit of using multi-site to help solve this problem unless we modify the shared parent theme (not recommended by CBOX)... If we decide we can modify the parent theme, then we could we place the PWA functionality there so it's not duplicated, and wrap the PWA code in conditional tags to switch to different PWA configurations, based on the value of home_url() for example.  

**Abstract PWA functionality away from themes, make it a plugin:** 
This would work on stand-alone or multi-site... we could create a plugin where there are per-site settings. This is the cleanest way, more effort, but has the most benefits going forward for reusability on other sites.
