### ISSUE TITLE
google maps pricing evaluation 

### ISSUE THREAD

**Issue by bdolor** [BCcampus/tlpd#53]
### Description 

Google has started charging for the use of its API. Events Manager functionality is integrated tightly with Google maps. 

https://wp-events-plugin.com/documentation/google-maps/api-usage/
https://wp-events-plugin.com/blog/2018/07/17/google-maps-api-pricing-increases/
https://cloud.google.com/maps-platform/pricing/sheet/
https://cloud.google.com/maps-platform/user-guide/

**Expected behaviour** 

Would like to evaluate the current API token used in all sites that use the map and transition the API token to a BCcampus controlled account, OR look at other options for a map service, or manage the potential costs associated with using the API. 

**Actual behaviour** 

We know very little at this point about what the impact could be.

**Comment by alex-418** [comment]
Here's the API limits and pricing: 

![pricing](https://user-images.githubusercontent.com/17072191/45766316-198ac180-bbec-11e8-906b-d6f65da9cdb5.png)

**Comment by dshaykewich** [comment]
When Mirjam is back, I will work with her to setup a new account (with payment card).  We can then transition @bdolor 's account away from the config.

For the near term, @bdolor , could you please confirm if you have the Events plugin using "Embedded Maps" (rather than dynamic ones)?  For now, these appear to be completely free (though less customizable).
https://wp-events-plugin.com/documentation/google-maps/map-types/#embedded-maps
https://developers.google.com/maps/billing/understanding-cost-of-use?#embed

**Comment by bdolor** [comment]
Confirming that _**Dynamic maps**_ is what the default is for events manager is and what we are using on both ey/ltpd sites. Allows for text balloons on the map, a feature used, at least on eypd/earlyyears to display location/event data: 

https://wp-events-plugin.com/documentation/google-maps/map-types/#dynamic-maps

![image](https://user-images.githubusercontent.com/2048170/45785826-a3558180-bc22-11e8-8c2b-948b3b572b6a.png)

**Comment by dshaykewich** [comment]
OK - we should keep an eye on the usage stats.  Looks like after 28k map loads/month, they'll start charging.

We can ask the project sponsors if there is ongoing budget to cover 'Dynamic maps' costs, or if we should revert to 'Embedded' ones.

**Comment by dshaykewich** [comment]
Sent email to stakeholders re: requesting direction on choosing map types.

**Comment by dshaykewich** [comment]
Status quo.  

Update Google account to devops@bccampus.ca account.
