### ISSUE TITLE
Change format for how dates are displayed

### ISSUE THREAD

**Issue by dshaykewich** [BCcampus/tlpd#74]
### Description 
Change how dates are displayed to spelled-out  version e.g. July 30, 2018 instead of 30/07/2018

![image](https://user-images.githubusercontent.com/34721375/45653212-095bd080-ba8c-11e8-9927-74c448fbe1bd.png)

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by jgrajkowski** [comment]
Changed to F j, Y (Sept 19, 2018) per https://codex.wordpress.org/Formatting_Date_and_Time

Retained jquery for Date Picker setup for now: dd/mm/yy

**Comment by BCcLeva** [comment]
@jgrajkowski for the Text under "Events" column can you make the title of the event bold instead of the location bold?  It looks like the location is both bold and italic. Maybe more readable for title of the event to be bold and the location to be italic only? Or does it displays this way bec. the title is dark green and the location is black?

**Comment by BCcLeva** [comment]
@jgrajkowski for the Text under "Events" column can you make the title of the event bold instead of the location bold? It looks like the location is both bold and italic. Maybe more readable for title of the event to be bold and the location to be italic only? Or does it displays this way bec. the title is dark green and the location is black? (Is this a new issue?)

**Comment by jgrajkowski** [comment]
That's CSS I can't control.

**Comment by jgrajkowski** [comment]
Moving back to backlog for CSS edit

**Comment by bdolor** [comment]
Since there is no more work to be done for changing the format of the dates, consider moving this to Done. Any new work that can be captured in a new ticket should be put there and discussed. As it is, if the title of the event is a link and is styled according to how links are styled.
