### ISSUE TITLE
Allow Event Contributor to Add an Online Event without a start and end date

### ISSUE THREAD

**Issue by paulagaube** [BCcampus/tlpd#85]
### Description 

As a teaching and learning centre staff person and contributor to TLPD, 
I want to be able to add online courses to the site which have no start or end date
So that learners will have a single listing of pro-d opportunities (whether they have fixed dates or are continuous entry).

AC
 - Uses the same form and attributes as events (except for dates)
 - Can find online events in search results
 - Can filter online events in location

Event contributors need to be able to add online events that have continuous entry or no specific start and end date. These events also may have no specific location except "online".

**Expected behaviour** 

Specify that an online event is available without having to add a start or end date. 

Also: decide if we require a location for the event (such as the contributors' location)

**Actual behaviour** 

"When" Start and End dates are required.
"Where" Location is required.

### Steps to reproduce the problem

[First Step, Second Step, etc]

### System Information

- TLPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by alex-418** [comment]
This might be solved by creating recurring events, please see documentation at https://wp-events-plugin.com/documentation/creating-and-editing-events/ to see if that will meet your needs.

**Comment by bdolor** [comment]
Paula and Kelsey will investigate and report back before any technical work proceeds.

**Comment by kkilbey** [comment]
@paulagaube and I have been investigating this issue, and we think it warrants more discussion about the process of posting an online event (as well as some revision to this ticket), @BCcLeva.

Because the Events Manager plugin requires a start/end date and a location, these are our current "work-arounds" for online events:

**Location**

We've added "Web" as the default location on the Post an Event page. This is a handy default because it can still be changed to a real location for in-person events, but provides one consistent location for all online events. Contributors posting online events won't have to wonder how to fill in the location field, and we won't have to worry about cleaning up duplicate locations as Admins (for online events only). Also, setting "Web" as the location for online events is clearer than using the event host's address, especially in the context of the "Upcoming Events" list on the Homepage, where a physical location may confuse users searching for online events.

**Date/Time**

We tested a few different methods for posting an online event that has continuous entry, and these are the settings that work best for now:
- This is a recurring event
- All Day
- Repeats Daily every 1 day
- Each event spans 0 days

With these settings, a separate event will be created every day for the duration of the date span chosen (e.g., if the dates are set to December 15, 2018 - December 14, 2019, then 365 separate events will be created). The whole calendar will be populated. However, the events will display correctly in the Upcoming Events menus and on the Events page; they will appear in order by date and will not crowd out other events, which will also still appear in order by date.

**Ideas for Discussion**

These work-arounds may do the trick, but here are some ideas for further discussion:
- @paulagaube has added an "Online Courses" calendar to the left side menu, visible from the Events page, here: https://tlpddev.bccampus.ca/events/ Dividing online and in-person events in these side bar calendars could resolve the problem with continuous-entry online events appearing on every single day of the calendar.
- @paulagaube has also added "Online" to the list of categories in the Post an Event page. We could use this category to separate out online events for the calendar mentioned above, to search for online courses only, etc.
- On the Post an Event page, it may be useful to move the "Online" custom field to the top of the page. Then, if a Contributor selects, "Yes, Online," instructions could pop up for the work-arounds described above. This would help Contributors avoid confusion when filling in Date/Time for an online event, and show them which settings to choose for a recurring online event.
- An alternative to pop-up instructions (but potentially more complicated): we could have a radio button at the top of the Post an Event page that says, "Is this an online event?" If the button is selected, it could automatically fill in certain fields ("Web" location, "Online" category, etc.) or somehow streamline the page for posting an online event.

Sorry for the long comment, everyone! Lots to discuss.

**Comment by paulagaube** [comment]
@kkilbey @BCcLeva - to comment on Kelsey's notes, I changed the location name from "Web" to "Online" this afternoon as I think it looks better, but just in case you wonder where the "Web" location is.... look for "Online" instead. 

Also, as Kelsey mentioned, it looks like there is a way to display a list of events based on their associated Category, and I thought this would be a good way to separate out the Online events, (including them or excluding them) but it doesn't look  like the widget I created for the left side bar is displaying now. And maybe those categories are WordPress categories and not BuddyPress Categories. It's a bit confusing. Perhaps next week I'll have a fresher mind and eye.

**Comment by paulagaube** [comment]
@BCcLeva Discussed this with Brad in our morning standup. Need to discuss the "online" issue with you. There are three places Online is currently indicated/chosen when adding an event: Category, Attribute, Location.
I had added the Category "Online" to CERT but have since removed it. The Category "Online Learning" still exists on PROD.

We suggest removing the Attribute "Online:  Yes/No" on the Add Event page, as this field is confusing and not used consistently. (This appears in the bottom of the page, in the "blob")

By creating the Location "Online", we have figured out how to use recurring events to list those online events. Brad says he can add logic to the "Location" field, so if Location = Online, then he could perhaps automagically fill in the suggested/required recurring event fields.

Returning this to the backlog so we can discuss.

**Comment by BCcLeva** [comment]
This sounds like a good solution. The Attribute Online: Yes/No is at best, clunky.

**Comment by bdolor** [comment]
I will remove the attribute value for online

**Comment by BCcLeva** [comment]
Well DONE and DONE Well. Thanks.
